---
# tasks file for role-media_server
- name: Setup socket-proxy docker network
  community.docker.docker_network:
    name: socket_proxy
    driver: bridge
    ipam_config:
      - subnet: 10.0.0.0/24

- name: Setup default network
  community.docker.docker_network:
    name: default
    driver: bridge
    ipam_config:
      - subnet: 11.0.0.0/24

# Set facts ###################################################
- name: Get UID of media_server_username
  ansible.builtin.getent:
    database: passwd
    key: "{{ media_server_username }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set UID var
  ansible.builtin.set_fact:
    uid: "{{ getent_passwd[media_server_username][1] }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set media_server_appdata based on media_server_username var
  ansible.builtin.set_fact:
    media_server_appdata: "{{ getent_passwd[media_server_username][4] }}/docker"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Get GID of media_server_username
  ansible.builtin.getent:
    database: group
    key: "{{ media_server_groupname }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set GID var
  ansible.builtin.set_fact:
    gid: "{{ getent_group[media_server_groupname][1] }}"
  ignore_errors: "{{ ansible_check_mode }}"

# Setup containers #############################################
- name: Setup the docker socket-proxy
  ansible.builtin.include_tasks: socket-proxy.yml

- name: Setup portainer
  ansible.builtin.include_tasks: portainer.yml

- name: Setup dozzle
  ansible.builtin.include_tasks: dozzle.yml

- name: Setup homepage
  ansible.builtin.include_tasks: homepage.yml

- name: Setup emby
  ansible.builtin.include_tasks: emby.yml

- name: Setup sabnzbd
  ansible.builtin.include_tasks: sabnzbd.yml

- name: Setup radarr
  ansible.builtin.include_tasks: radarr.yml

- name: Setup sonarr
  ansible.builtin.include_tasks: sonarr.yml

- name: Setup bazarr
  ansible.builtin.include_tasks: bazarr.yml
