---
- name: Ensure portainer appdata directory
  ansible.builtin.file:
    path: "{{ media_server_appdata }}/appdata/portainer/data"
    state: directory
    owner: "{{ media_server_username }}"
    group: "{{ media_server_groupname }}"
    mode: "0750"

- name: Setup portainer
  community.docker.docker_container:
    name: portainer-new
    image: portainer/portainer-ce:latest
    security_opts:
      - no-new-privileges:true
    restart_policy: "unless-stopped"
    networks:
      - name: socket_proxy
    command: -H tcp://socket-proxy:2375
    ports:
      - "9001:9000"
    volumes:
      - "{{ media_server_appdata }}/appdata/portainer/data:/data"
    env:
      TZ: "{{ media_server_tz }}"
  ignore_errors: "{{ ansible_check_mode }}"
