---
- name: Ensure radarr appdata directory
  ansible.builtin.file:
    path: "{{ media_server_appdata }}/appdata/radarr/downloads"
    state: directory
    owner: "{{ media_server_username }}"
    group: "{{ media_server_groupname }}"
    mode: "0750"

- name: Setup radarr
  community.docker.docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr:latest
    security_opts:
      - no-new-privileges:true
    restart_policy: "unless-stopped"
    networks:
      - name: default
    ports:
      - "7878:7878"
    volumes:
      - "{{ media_server_appdata }}/appdata/radarr:/config"
      - "{{ media_server_appdata }}/appdata/radarr/downloads:/data/downloads"
      - "{{ media_server_movies }}:/movies"
      - "{{ media_server_tv }}:/tv"
    env:
      TZ: "{{ media_server_tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
  ignore_errors: "{{ ansible_check_mode }}"
