---
- name: Ensure sabnzbd appdata directory
  ansible.builtin.file:
    path: "{{ media_server_appdata }}/appdata/sabnzbd/Downloads"
    state: directory
    owner: "{{ media_server_username }}"
    group: "{{ media_server_groupname }}"
    mode: "0750"

- name: Setup sabnzbd
  community.docker.docker_container:
    name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    security_opts:
      - no-new-privileges:true
    restart_policy: "unless-stopped"
    networks:
      - name: service_network
    ports:
      - "8888:8080"
    volumes:
      - "{{ media_server_appdata }}/appdata/sabnzbd:/config"
      - "{{ media_server_appdata }}/appdata/sabnzbd/Downloads:/incomplete-downloads"
      - "{{ media_server_tv }}:/downloads/tv"
      - "{{ media_server_movies }}:/downloads/movies"
    env:
      TZ: "{{ media_server_tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
  ignore_errors: "{{ ansible_check_mode }}"
